// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqbgubgraghyxfzshhpj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxYmd1YmdyYWdoeXhmenNoaHBqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk0MjAyNzksImV4cCI6MjA4NDk5NjI3OX0.Q_pcMCHJmjEp_Y36wRPJZU5g29tTfOU8QLuakNI6eeM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});